package bot

import "meethalf-telegram-bot/internal/domain"

var messageCatalogUkrainian = map[messageKey]string{
	msgDefaultHelp:                      "Meethalf допомагає знаходити людей за інтересами та вайбом. Розкажіть, кого хочете зустріти, а решту зробимо ми.",
	msgUnknownCommand:                   "Я не впізнав цю команду. Спробуйте кнопки нижче.",
	msgAdminBadge:                       "Доступ адміністратора увімкнено. Ви керуєте.",
	msgModeratorBadge:                   "Доступ модератора увімкнено. Дякуємо за безпеку.",
	msgAdminMenu:                        "Адмін-панель — оберіть дію.",
	msgModeratorMenu:                    "Панель модератора — оберіть дію.",
	msgAdminAccessDenied:                "Для цієї дії потрібен доступ адміністратора.",
	msgAdminModerationRestricted:        "Модератори можуть діяти лише щодо звичайних користувачів.",
	msgAdminUsersEmpty:                  "Користувачів поки немає.",
	msgAdminUsersLoadFailed:             "Не вдалося завантажити користувачів. Спробуйте ще раз пізніше.",
	msgAdminUsersPage:                   "Користувачів: %d всього. Показано %d–%d.",
	msgAdminUsersEmptyPage:              "Користувачів: %d всього. На цій сторінці порожньо.",
	msgAdminBannedUsersEmpty:            "Забанених користувачів немає.",
	msgAdminBannedUsersLoadFailed:       "Не вдалося завантажити забанених користувачів. Спробуйте пізніше.",
	msgAdminBannedUsersPage:             "Забанених користувачів: %d всього. Показано %d–%d.",
	msgAdminBannedUsersEmptyPage:        "Забанених користувачів: %d всього. На цій сторінці порожньо.",
	msgAdminShadowBannedUsersEmpty:      "Тіньово забанених користувачів немає.",
	msgAdminShadowBannedUsersLoadFailed: "Не вдалося завантажити тіньово забанених користувачів. Спробуйте пізніше.",
	msgAdminShadowBannedUsersPage:       "Тіньово забанених користувачів: %d всього. Показано %d–%d.",
	msgAdminShadowBannedUsersEmptyPage:  "Тіньово забанених користувачів: %d всього. На цій сторінці порожньо.",
	msgAdminHiddenUsersEmpty:            "Прихованих профілів немає.",
	msgAdminHiddenUsersLoadFailed:       "Не вдалося завантажити приховані профілі. Спробуйте пізніше.",
	msgAdminHiddenUsersPage:             "Прихованих профілів: %d всього. Показано %d–%d.",
	msgAdminHiddenUsersEmptyPage:        "Прихованих профілів: %d всього. На цій сторінці порожньо.",
	msgAdminModeratorsEmpty:             "Модераторів поки немає.",
	msgAdminModeratorsLoadFailed:        "Не вдалося завантажити модераторів. Спробуйте пізніше.",
	msgAdminModeratorsPage:              "Модераторів: %d всього. Показано %d–%d.",
	msgAdminModeratorsEmptyPage:         "Модераторів: %d всього. На цій сторінці порожньо.",
	msgAdminReportsEmpty:                "Скарг поки немає.",
	msgAdminReportsLoadFailed:           "Не вдалося завантажити скарги. Спробуйте пізніше.",
	msgAdminReportsPage:                 "Користувачів зі скаргами: %d всього. Показано %d–%d.",
	msgAdminReportsEmptyPage:            "Користувачів зі скаргами: %d всього. На цій сторінці порожньо.",
	msgAdminBanUsage:                    "Надішліть ID користувача або @username, щоб забанити.",
	msgAdminBanFailed:                   "Не вдалося забанити користувача. Спробуйте пізніше.",
	msgAdminUserNotFound:                "Користувача не знайдено. Перевірте ID або @username.",
	msgAdminBanSuccess:                  "Користувача %s забанено.",
	msgAdminUnbanUsage:                  "Надішліть ID користувача або @username, щоб зняти бан.",
	msgAdminUnbanFailed:                 "Не вдалося зняти бан з користувача. Спробуйте пізніше.",
	msgAdminUnbanSuccess:                "Бан з користувача %s знято.",
	msgAdminShadowBanUsage:              "Надішліть ID користувача або @username, щоб застосувати тіньовий бан.",
	msgAdminShadowBanFailed:             "Не вдалося застосувати тіньовий бан. Спробуйте пізніше.",
	msgAdminShadowBanSuccess:            "Користувачу %s застосовано тіньовий бан.",
	msgAdminShadowUnbanUsage:            "Надішліть ID користувача або @username, щоб зняти тіньовий бан.",
	msgAdminShadowUnbanFailed:           "Не вдалося зняти тіньовий бан. Спробуйте пізніше.",
	msgAdminShadowUnbanSuccess:          "Тіньовий бан знято для %s.",
	msgAdminHideProfileUsage:            "Надішліть ID користувача або @username, щоб приховати профіль.",
	msgAdminHideProfileFailed:           "Не вдалося приховати профіль. Спробуйте пізніше.",
	msgAdminHideProfileSuccess:          "Профіль %s приховано.",
	msgAdminShowProfileUsage:            "Надішліть ID користувача або @username, щоб показати профіль.",
	msgAdminShowProfileFailed:           "Не вдалося показати профіль. Спробуйте пізніше.",
	msgAdminShowProfileSuccess:          "Профіль %s знову видимий.",
	msgAdminViewProfileUsage:            "Надішліть ID користувача або @username, щоб переглянути профіль.",
	msgAdminViewProfileFailed:           "Не вдалося завантажити профіль. Спробуйте пізніше.",
	msgAdminDeleteProfileUsage:          "Надішліть ID користувача або @username, щоб видалити профіль.",
	msgAdminDeleteProfileFailed:         "Не вдалося видалити профіль. Спробуйте пізніше.",
	msgAdminDeleteProfileSuccess:        "Профіль %s видалено.",
	msgAdminActionFailed:                "Не вдалося виконати дію адміністратора. Спробуйте пізніше.",
	msgAdminModeratorUsage:              "Надішліть ID користувача або @username, щоб надати права модератора.",
	msgAdminModeratorFailed:             "Не вдалося надати права модератора. Спробуйте пізніше.",
	msgAdminModeratorSuccess:            "Користувач %s тепер модератор.",
	msgAdminUnmoderatorUsage:            "Надішліть ID користувача або @username, щоб зняти права модератора.",
	msgAdminUnmoderatorFailed:           "Не вдалося зняти права модератора. Спробуйте пізніше.",
	msgAdminUnmoderatorSuccess:          "Користувач %s більше не модератор.",
	msgAdminResetChoicesUsage:           "Надішліть ID користувача або @username, щоб скинути рішення по матчах.",
	msgAdminResetChoicesFailed:          "Не вдалося скинути рішення по матчах. Спробуйте пізніше.",
	msgAdminResetChoicesSuccess:         "Рішення по матчах для %s скинуто.",
	msgAdminResetStartUsage:             "Надішліть ID користувача або @username, щоб скинути перевірку 16+.",
	msgAdminResetStartFailed:            "Не вдалося скинути перевірку 16+. Спробуйте пізніше.",
	msgAdminResetStartSuccess:           "Перевірку 16+ для %s скинуто.",
	msgAdminClearReportsUsage:           "Надішліть ID користувача або @username, щоб очистити скарги.",
	msgAdminClearReportsFailed:          "Не вдалося очистити скарги. Спробуйте пізніше.",
	msgAdminClearReportsSuccess:         "Скарги для %s очищено.",
	msgAdminAdUsage:                     "Надішліть текст оголошення та необов'язкове фото у будь-якому порядку. Використайте кнопки нижче, щоб додати посилання, переглянути або надіслати розсилку.",
	msgAdminAdFailed:                    "Не вдалося надіслати оголошення. Спробуйте пізніше.",
	msgAdminAdQueued:                    "Розсилку оголошення розпочато. Я надішлю підсумок тут, коли все завершиться.",
	msgAdminAdSummary:                   "Розсилку оголошення завершено. Одержувачі: %d. Надіслано: %d. Помилок: %d. Пропущено: %d.",
	msgAdminAdSummaryFailed:             "Розсилку оголошення завершено з помилками. Одержувачі: %d. Надіслано: %d. Помилок: %d. Пропущено: %d.",
	msgAdminAdTooLong:                   "Текст оголошення занадто довгий. Максимум %d символів.",
	msgAdminAdDraftStatus:               "Чернетку оголошення оновлено.\nТекст: %s\nФото: %s\nКнопки: %d.",
	msgAdminAdButtonUsage:               "Надішліть кнопку у форматі: Назва | https://example.com",
	msgAdminAdButtonAdded:               "Кнопку додано. Всього кнопок: %d.",
	msgAdminAdPreviewSent:               "Попередній перегляд надіслано нижче.",
	msgUserBanned:                       "Ваш акаунт заблоковано. Якщо це помилка, зверніться в підтримку.",
	msgProfileCreated:                   "Ваш профіль готовий! 🎉",
	msgProfileUpdated:                   "Профіль оновлено — виглядає чудово!",
	msgLoadingStart:                     "Готуємо ваш профіль...",
	msgLoadingProfileView:               "Завантажуємо ваш профіль...",
	msgLoadingProfilePreview:            "Готуємо попередній перегляд профілю...",
	msgLoadingEditName:                  "Відкриваємо редагування імені...",
	msgLoadingEditGender:                "Відкриваємо вибір статі...",
	msgLoadingEditBirthDate:             "Відкриваємо редагування дати народження...",
	msgLoadingEditCountry:               "Відкриваємо вибір країни...",
	msgLoadingEditCity:                  "Відкриваємо вибір міста...",
	msgLoadingEditDesc:                  "Відкриваємо редагування опису...",
	msgLoadingEditEmoji:                 "Відкриваємо вибір емодзі...",
	msgLoadingEditPhotos:                "Відкриваємо керування фото...",
	msgLoadingProfileVisibility:         "Оновлюємо видимість у пошуку...",
	msgLoadingProfileLikeNotifications:  "Оновлюємо сповіщення про лайки...",
	msgLoadingSearchStart:               "Шукаємо збіги...",
	msgLoadingSearchNext:                "Шукаємо наступний профіль...",
	msgLoadingSearchPrev:                "Відкриваємо попередній профіль...",
	msgLoadingSearchAI:                  "Аналізуємо ваш запит...",
	msgLoadingSearchHistory:             "Завантажуємо вашу історію...",
	msgLoadingSearchHistoryProfile:      "Відкриваємо профіль з історії...",
	msgLoadingSearchHistoryAction:       "Зберігаємо ваше рішення...",
	msgLoadingLikesList:                 "Завантажуємо ваші лайки...",
	msgLoadingLikesProfile:              "Відкриваємо профіль...",
	msgLoadingAdminUsers:                "Завантажуємо користувачів...",
	msgLoadingAdminBan:                  "Застосовуємо бан...",
	msgLoadingAdminUnban:                "Знімаємо бан...",
	msgLoadingAdminShadowBan:            "Застосовуємо тіньовий бан...",
	msgLoadingAdminShadowUnban:          "Знімаємо тіньовий бан...",
	msgLoadingAdminHiddenUsers:          "Завантажуємо приховані профілі...",
	msgLoadingAdminHideProfile:          "Приховуємо профіль...",
	msgLoadingAdminShowProfile:          "Показуємо профіль...",
	msgLoadingAdminViewProfile:          "Завантажуємо профіль...",
	msgLoadingAdminDeleteProfile:        "Видаляємо профіль...",
	msgLoadingAdminModerator:            "Надаємо права модератора...",
	msgLoadingAdminUnmoderator:          "Знімаємо права модератора...",
	msgLoadingAdminResetChoices:         "Скидаємо рішення по матчах...",
	msgLoadingAdminResetStart:           "Скидаємо перевірку 16+...",
	msgLoadingAdminClearReports:         "Очищаємо скарги...",
	msgLoadingAdminAd:                   "Запускаємо розсилку оголошення...",
	msgLoadingAdminBannedUsers:          "Завантажуємо забанених користувачів...",
	msgLoadingAdminShadowBannedUsers:    "Завантажуємо тіньово забанених користувачів...",
	msgLoadingAdminModerators:           "Завантажуємо модераторів...",
	msgLoadingAdminReports:              "Завантажуємо скарги...",
	msgCreatingProfile:                  "Створюємо ваш профіль...",
	msgUpdatingProfile:                  "Зберігаємо оновлення...",
	msgDeletingProfile:                  "Видаляємо ваш профіль...",
	msgProfileDeleteConfirm:             "Видалити профіль? Цю дію не можна скасувати.",
	msgProfileDeleteCanceled:            "Видалення скасовано. Профіль залишено.",
	msgProfileDeleteExpired:             "Запит на видалення прострочено. Відкрийте Налаштування, щоб спробувати знову.",
	msgProfileSetupCanceled:             "Створення профілю скасовано. Ви знову в меню.",
	msgProfileEditCanceled:              "Редагування профілю скасовано. Ви знову в меню.",
	msgActionCanceled:                   "Дію скасовано.",
	msgProfileHidden:                    "Ваш профіль тепер прихований у пошуку.",
	msgProfileVisible:                   "Ваш профіль знову видимий у пошуку.",
	msgProfileVisibilityUpdateFailed:    "Не вдалося оновити видимість у пошуку. Спробуйте пізніше.",
	msgLikesNotificationsEnabled:        "Сповіщення про лайки увімкнено.",
	msgLikesNotificationsDisabled:       "Сповіщення про лайки вимкнено.",
	msgLikesNotificationsUpdateFailed:   "Не вдалося оновити сповіщення про лайки. Спробуйте пізніше.",
	msgSearchGenderPrompt:               "Кого ви шукаєте? Оберіть стать.",
	msgSearchAccuracyPrompt:             "Оберіть точність підбору (0–4).\n0 — ширший пошук з більшою різноманітністю.\n4 — суворіший пошук із ближчими збігами.",
	msgSearchAccuracyEnabled:            "Розширений пошук увімкнено.",
	msgSearchAccuracyDisabled:           "Розширений пошук вимкнено.",
	msgSearchAccuracyUpdateFailed:       "Не вдалося оновити розширений пошук. Спробуйте пізніше.",
	msgSearchAIPrompt:                   "Розкажіть, що важливо: стать, вік, місто та кілька рис або інтересів.\nПриклад: «Жінка 25–30, Москва, любить мистецтво, подорожі та походи».",
	msgSearchAITooShort:                 "Додайте трохи більше деталей, щоб ШІ міг допомогти.",
	msgSearchAIUnavailable:              "Пошук з ШІ зараз недоступний. Спробуйте пізніше.",
	msgSearchNoCandidates:               "Поки немає збігів. Спробуйте трохи пізніше.",
	msgSearchNoPrevious:                 "Немає попереднього профілю для повернення.",
	msgSearchHistoryEmpty:               "Ваша історія порожня.",
	msgSearchStartRequired:              "Натисніть «Почати знайомства», щоб розпочати.",
	msgSearchProfileMissing:             "Спершу створіть профіль, щоб почати знайомства та переглядати анкети.",
	msgSearchUnavailable:                "Пошук зараз недоступний.",
	msgSearchActionFailed:               "Не вдалося обробити дію. Спробуйте пізніше.",
	msgSearchHistoryPage:                "Історія: %d всього. Показано %d–%d.",
	msgSearchHistoryEmptyPage:           "Історія: %d всього. На цій сторінці порожньо.",
	msgSearchHistoryAction:              "Поточне рішення: %s.\nЩо хочете зробити?",
	msgLikesListEmpty:                   "Поки немає лайків.",
	msgLikesListEmptyPage:               "Лайків: %d всього. На цій сторінці порожньо.",
	msgLikesListPage:                    "Лайків: %d всього. Показано %d–%d.",
	msgLikesListLine:                    "%d. %s",
	msgMatchActions:                     "Що хочете зробити?",
	msgMatchActionSaved:                 "Рішення збережено.",
	msgMatchProfileNotFound:             "Профіль не знайдено.",
	msgProfileViewRequiresProfile:       "Спершу створіть профіль, щоб переглядати інших.",
	msgMatchSuccess:                     "Це матч! Ви та %s вподобали одне одного. 🎉",
	msgMatchNickname:                    "Нікнейм: %s",
	msgNamePromptNoTelegram:             "У вашому профілі Telegram поки немає імені. Введіть ім'я, яке хочете використовувати.",
	msgNamePromptWithTelegram:           "Ім'я в Telegram: %s\nНатисніть нижче, щоб використати його, або введіть інше.",
	msgBotCheckPrompt:                   "Швидка перевірка на бота: %s\nОберіть правильну відповідь нижче.",
	msgBirthDatePrompt:                  "Введіть дату народження у форматі %s (наприклад, %s).",
	msgGenderPrompt:                     "Оберіть свою стать.",
	msgCountryPrompt:                    "Оберіть свою країну.",
	msgCityPrompt:                       "Оберіть своє місто.",
	msgDescriptionPrompt:                "Розкажіть трохи про себе.",
	msgEmojiPrompt:                      "Оберіть емодзі, що найкраще вас описує.",
	msgPhotosPrompt:                     "Надішліть 1–4 фото для альбому. Натисніть «Готово», коли завершите.",
	msgProfileEditMenu:                  "Що хочете оновити?",
	msgProfileSettings:                  "Налаштування профілю. Кнопками нижче можна керувати видимістю, розширеним пошуком, сповіщеннями про лайки, мовою або видалити профіль.",
	msgProfileSettingsWithVisibility:    "Налаштування профілю.\nВидимість у пошуку: %s.\nРозширений пошук: %s.\nСповіщення про лайки: %s.\nКнопками нижче можна керувати видимістю, розширеним пошуком, сповіщеннями про лайки, мовою або видалити профіль.",
	msgProfileActions:                   "Натисніть нижче, щоб переглянути або відредагувати профіль.",
	msgProfilePreviewActions:            "Натисніть нижче, щоб повернутися або відредагувати профіль.",
	msgEditNamePrompt:                   "Введіть нове ім'я.",
	msgEditBirthDatePrompt:              "Введіть нову дату народження у форматі %s (наприклад, %s).",
	msgEditGenderPrompt:                 "Оберіть нову стать.",
	msgEditCountryPrompt:                "Оберіть нову країну.",
	msgEditCityPrompt:                   "Оберіть нове місто.",
	msgEditDescriptionPrompt:            "Напишіть новий опис.",
	msgEditEmojiPrompt:                  "Оберіть новий емодзі.",
	msgEditPhotosPrompt:                 "Надішліть 1–4 фото, щоб замінити альбом. Натисніть «Готово», коли завершите.",
	msgEditDefaultPrompt:                "Введіть нове значення.",
	msgProfileDetailsHeader:             "Ваш профіль:",
	msgProfilePreviewFallbackName:       "Анкета",
	msgProfileEditHeader:                "Редагування профілю: %s",
	msgProfileSetupHeader:               "Створимо ваш профіль (крок %d/%d): %s\n%s",
	msgProfileSetupEstimate:             "Орієнтовний час: ~%d хв",
	msgStartGreeting:                    "Вітаємо в Meethalf! Готові познайомитися?",
	msgStartGreetingNamed:               "Вітаємо в Meethalf, %s! Готові познайомитися?",
	msgProfileNotFoundCreateButton:      "Профіль не знайдено. Натисніть «Створити профіль», щоб почати.",
	msgProfileNotFoundButtonBelow:       "Профіль не знайдено. Натисніть кнопку нижче, щоб створити його.",
	msgProfileNotFoundUseProfile:        "Профіль не знайдено. Надішліть /profile, щоб створити його.",
	msgProfileDeleted:                   "Профіль видалено. Натисніть «Створити профіль», щоб зробити новий.",
	msgProfileDeletedDraftWarning:       "Профіль видалено. Примітка: не вдалося очистити чернетку профілю.",
	msgProfileDeletedDraftWarningOnly:   "Примітка: не вдалося очистити чернетку профілю.",
	msgProfileSetupUnavailable:          "Створення профілю зараз недоступне.",
	msgProfileSetupUnavailableChat:      "Створення профілю недоступне в цьому чаті.",
	msgProfileSetupStartFailed:          "Не вдалося розпочати створення профілю. Спробуйте пізніше.",
	msgProfileSetupLoadFailed:           "Не вдалося завантажити створення профілю. Спробуйте пізніше.",
	msgProfileSetupNotActive:            "Створення профілю не активне. Надішліть /profile, щоб почати.",
	msgProfileSetupSaveFailed:           "Не вдалося зберегти створення профілю. Спробуйте пізніше.",
	msgProfileEditUnavailable:           "Редагування профілю зараз недоступне.",
	msgProfileEditUnavailableChat:       "Редагування профілю недоступне в цьому чаті.",
	msgProfileServiceUnavailable:        "Сервіс профілю зараз недоступний.",
	msgProfileLoadFailed:                "Не вдалося завантажити ваш профіль. Спробуйте пізніше.",
	msgProfileDeleteUnavailable:         "Видалення профілю зараз недоступне.",
	msgProfileDeleteUnavailableChat:     "Видалення профілю недоступне в цьому чаті.",
	msgProfileDeletePrepareFailed:       "Не вдалося підготувати видалення профілю. Спробуйте пізніше.",
	msgProfileDeleteFailed:              "Не вдалося видалити профіль. Спробуйте пізніше.",
	msgProfileDeleteCancelFailed:        "Не вдалося скасувати видалення профілю. Спробуйте пізніше.",
	msgProfileEditStartFailed:           "Не вдалося розпочати редагування профілю. Спробуйте пізніше.",
	msgProfileEditSaveFailed:            "Не вдалося зберегти зміни профілю. Спробуйте пізніше.",
	msgProfileSaveFailed:                "Не вдалося зберегти профіль. Спробуйте пізніше.",
	msgBotCheckTooManyAttempts:          "Занадто багато спроб — спробуємо нову перевірку.",
	msgBotCheckIncorrect:                "Неправильно. Спробуйте ще раз.",
	msgNamePromptEmpty:                  "Будь ласка, введіть ім'я.",
	msgNamePromptEmptyCreate:            "Будь ласка, введіть ім'я або використайте ім'я з Telegram нижче.",
	msgNamePromptTelegramMissing:        "У вашому профілі Telegram поки немає імені. Введіть ім'я, яке хочете використовувати.",
	msgNameTooLong:                      "Ім'я занадто довге — максимум %d символів.",
	msgGenderInvalid:                    "Будь ласка, оберіть: чоловік, жінка або інше.",
	msgBirthDateInvalid:                 "Дата народження має бути у форматі %s (наприклад, %s). Спробуйте ще раз.",
	msgAgeConfirmPrompt:                 "Щоб користуватися Meethalf, підтвердьте, що вам щонайменше %d років. Підтверджуючи, ви засвідчуєте відповідність мінімальному віку.",
	msgAgeConfirmDeclined:               "Ботом можуть користуватися лише %d+. Якщо це помилка, підтвердьте вік нижче.",
	msgAgeConfirmSaveFailed:             "Не вдалося підтвердити ваш вік. Спробуйте пізніше.",
	msgAgeTooYoung:                      "Вік має бути не менше %d. Перевірте дату народження.",
	msgAgeTooOld:                        "Вік має бути не більше %d. Перевірте дату народження.",
	msgAgeAccessDenied:                  "Доступ лише для користувачів %d+.",
	msgCountryInvalid:                   "Будь ласка, оберіть країну: Росія, Казахстан, Білорусь або Україна.",
	msgCityInvalid:                      "Будь ласка, оберіть місто зі списку вашої країни.",
	msgDescriptionEmpty:                 "Опис не може бути порожнім. Спробуйте ще раз.",
	msgDescriptionTooLong:               "Опис занадто довгий — максимум %d символів.",
	msgEmojiInvalid:                     "Будь ласка, оберіть емодзі зі списку.",
	msgPhotosNotEnough:                  "Надішліть щонайменше %d фото перед завершенням.",
	msgPhotosPromptRepeat:               "Надішліть 1–4 фото для альбому. Натисніть «Готово», коли завершите.",
	msgPhotosLimitReached:               "Ви досягли ліміту %d фото. Натисніть «Готово», щоб завершити.",
	msgPhotosProgress:                   "Фото в альбомі: %d/%d. Надішліть ще або натисніть «Готово».",
	msgProfileViewUnavailable:           "Перегляд профілю зараз недоступний.",
	msgProfileViewUnavailableChat:       "Перегляд профілю недоступний у цьому чаті.",
	msgProfileDeleteNoteDraft:           "Профіль видалено. Примітка: не вдалося очистити чернетку профілю.",
	msgAdminUserListNoName:              "Ім'я відсутнє",
	msgAdminUserListNA:                  "н/д",
	msgAdminUserListLine:                "%d. %s — ID %d, username %s, %s",
	msgAdminReportedUserListLine:        "%d. %s — ID %d, username %s, скарги: %d, %s",
	msgSearchHistoryLine:                "%d. %s — %s",
	msgSearchHistoryLineShort:           "%d) %s",
	msgSearchHistoryUserFallback:        "Користувач №%d",
	msgSearchHistoryLabel:               "%s • %s",
	msgAgeShort:                         "%d років",
	msgProfileDetailsLine:               "%s — %s",
	msgProfileDetailsPhotos:             "Фото в альбомі: %d",
	msgProfileDetailsCreated:            "Дата створення: %s",
	msgProfileDetailsUpdated:            "Останнє оновлення: %s",
	msgProfileDetailsDescriptionLabel:   "Про мене:\n%s",
	msgLikeNotification:                 "Вам поставили лайк ❤️. Переглянути профіль?",
	msgLikeNotificationFrom:             "Вам поставили лайк ❤️ від %s. Переглянути профіль?",
	msgLanguagePrompt:                   "Оберіть мову.",
	msgLanguageUpdated:                  "Мову оновлено. Готово!",
	msgLanguageUnsupported:              "Ця мова не підтримується. Оберіть доступний варіант.",
	msgProfileSettingsLanguageHint:      "Налаштування профілю. Без профілю можна лише змінити мову.",
}

var buttonCatalogUkrainian = map[buttonKey]string{
	btnCancel:                    "До головного меню",
	btnAgeConfirmYes:             "Так, мені 16+",
	btnAgeConfirmNo:              "Ні, мені менше 16",
	btnProfileSetupBack:          "Крок назад",
	btnProfileDeleteCancel:       "Залишити мій профіль",
	btnBackToProfile:             "До мого профілю",
	btnEditCancel:                "Скасувати редагування",
	btnSearchAccuracyCancel:      "Назад до статі",
	btnSearchRefresh:             "Оновити підбір",
	btnSearchHistory:             "Переглянуті анкети",
	btnSearchHistoryPrev:         "Попередні",
	btnSearchHistoryNext:         "Наступні",
	btnSearchHistoryBack:         "До списку",
	btnLikesInbox:                "Хто лайкнув мене",
	btnLikesBack:                 "Назад до лайків",
	btnAdminMenu:                 "Адмін-панель",
	btnModeratorMenu:             "Панель модератора",
	btnAdminUsers:                "Усі користувачі",
	btnAdminBan:                  "Забанити",
	btnAdminUnban:                "Розбанити",
	btnAdminShadowBan:            "Тіньовий бан",
	btnAdminShadowUnban:          "Зняти тіньовий бан",
	btnAdminHiddenUsers:          "Приховані профілі",
	btnAdminHideProfile:          "Приховати профіль",
	btnAdminShowProfile:          "Показати профіль",
	btnAdminViewProfile:          "Переглянути профіль",
	btnAdminDeleteProfile:        "Видалити профіль",
	btnAdminModerator:            "Надати модератора",
	btnAdminUnmoderator:          "Зняти модератора",
	btnAdminResetChoices:         "Скинути матчі",
	btnAdminResetStart:           "Скинути перевірку 16+",
	btnAdminPostAd:               "Розіслати оголошення",
	btnAdminBannedUsers:          "Бан-список",
	btnAdminShadowBannedUsers:    "Список тіньових банів",
	btnAdminModerators:           "Список модераторів",
	btnAdminReports:              "Скарги",
	btnAdminClearReports:         "Очистити скарги",
	btnAdminAdAddButton:          "Додати кнопку",
	btnAdminAdClearButtons:       "Очистити кнопки",
	btnAdminAdRemovePhoto:        "Прибрати фото",
	btnAdminAdPreview:            "Попередній перегляд",
	btnAdminAdSend:               "Надіслати",
	btnAdminUsersPrev:            "Попередні",
	btnAdminUsersNext:            "Наступні",
	btnAdminBackToMenu:           "Назад до адмін-меню",
	btnStartSearch:               "Почати знайомства",
	btnStartSearchAI:             "Пошук з ШІ",
	btnSearchAIRepeat:            "Спробувати ще раз",
	btnProfile:                   "Мій профіль",
	btnCreateProfile:             "Створити профіль",
	btnSettings:                  "Налаштування",
	btnPreviewProfile:            "Попередній перегляд",
	btnEditProfile:               "Редагувати профіль",
	btnDeleteProfile:             "Видалити профіль",
	btnDeleteConfirm:             "Так, видалити",
	btnProfileEditName:           "Ім'я в профілі",
	btnProfileEditGender:         "Моя стать",
	btnProfileEditBirthDate:      "Дата народження",
	btnProfileEditCountry:        "Моя країна",
	btnProfileEditCity:           "Моє місто",
	btnProfileEditDescription:    "Про мене",
	btnProfileEditEmoji:          "Мій емодзі",
	btnProfileEditPhotos:         "Мої фото",
	btnTelegramName:              "Взяти ім'я з Telegram",
	btnAlbumDone:                 "Готово",
	btnGenderMale:                "Чоловік",
	btnGenderFemale:              "Жінка",
	btnGenderOther:               "Інше",
	btnCountryRussia:             "Росія 🇷🇺",
	btnCountryKazakhstan:         "Казахстан 🇰🇿",
	btnCountryBelarus:            "Білорусь 🇧🇾",
	btnCountryUkraine:            "Україна 🇺🇦",
	btnSearchMen:                 "Чоловіки 👨",
	btnSearchWomen:               "Жінки 👩",
	btnSearchOther:               "Інше",
	btnSearchAny:                 "Будь-хто",
	btnReport:                    "Поскаржитися",
	btnBackToPreviousProfile:     "Попередній профіль",
	btnViewProfile:               "Відкрити профіль",
	btnHideFromSearch:            "Приховати мій профіль",
	btnShowInSearch:              "Показувати мій профіль",
	btnLanguage:                  "Мова",
	btnAdvancedSearchEnable:      "Розширений пошук: увімкнено",
	btnAdvancedSearchDisable:     "Розширений пошук: вимкнено",
	btnLikesNotificationsEnable:  "Сповіщення про лайки: увімкнено",
	btnLikesNotificationsDisable: "Сповіщення про лайки: вимкнено",
	btnAdvancedSearchStatus:      "Розширений пошук: %s",
	btnLikesNotificationsStatus:  "Сповіщення про лайки: %s",
	btnBackToSettings:            "Назад до налаштувань",
	btnLanguageEnglish:           "English 🇺🇸",
	btnLanguageRussian:           "Русский 🇷🇺",
	btnLanguageUkrainian:         "Українська 🇺🇦",
}

var labelCatalogUkrainian = map[labelKey]string{
	labelNotSet:             "Ще не вказано",
	labelUnknown:            "Невідоме значення",
	labelProfile:            "Анкета",
	labelStepVerification:   "Швидка перевірка",
	labelStepName:           "Ім'я для профілю",
	labelStepGender:         "Вибір статі",
	labelStepBirthDate:      "Дата народження",
	labelStepCountry:        "Країна/регіон",
	labelStepCity:           "Місто/селище",
	labelStepDescription:    "Про мене",
	labelStepEmoji:          "Емодзі-настрій",
	labelStepPhotos:         "Фотоальбом",
	labelGenderMale:         "Чоловік",
	labelGenderFemale:       "Жінка",
	labelGenderOther:        "Інше",
	labelCountryRussia:      "Росія 🇷🇺",
	labelCountryKazakhstan:  "Казахстан 🇰🇿",
	labelCountryBelarus:     "Білорусь 🇧🇾",
	labelCountryUkraine:     "Україна 🇺🇦",
	labelActionLike:         "Лайк",
	labelActionDislike:      "Пропуск",
	labelActionReport:       "Скарга",
	labelActionNone:         "Без дії",
	labelStatusBanned:       "заблоковано",
	labelStatusShadowBanned: "тіньовий бан",
	labelStatusModerator:    "Модератор",
	labelStatusHidden:       "приховано",
	labelStatusVisible:      "видимо",
	labelStatusEnabled:      "активно",
	labelStatusDisabled:     "неактивно",
	labelYes:                "Так",
	labelNo:                 "Ні",
	labelName:               "Ім'я в профілі",
	labelEmoji:              "Емодзі-настрій",
	labelGender:             "Гендер",
	labelAge:                "Вік (роки)",
	labelCountry:            "Країна/регіон",
	labelCity:               "Місто/селище",
	labelSearchVisibility:   "Видимість у пошуку",
	labelDescription:        "Про мене",
	labelPhotos:             "Фотоальбом",
	labelCreated:            "Дата створення",
	labelUpdated:            "Останнє оновлення",
	labelLanguageEnglish:    "Англійська 🇺🇸",
	labelLanguageRussian:    "Російська 🇷🇺",
	labelLanguageUkrainian:  "Українська 🇺🇦",
	labelThisUser:           "цей акаунт",
}

var cityLabelsUkrainian = map[string]string{
	"Moscow":           "Москва",
	"Saint Petersburg": "Санкт-Петербург",
	"Novosibirsk":      "Новосибірськ",
	"Krasnodar":        "Краснодар",
	"Omsk":             "Омськ",
	"Rostov-on-Don":    "Ростов-на-Дону",
	"Perm":             "Перм",
	"Krasnoyarsk":      "Красноярськ",
	"Yekaterinburg":    "Єкатеринбург",
	"Kazan":            "Казань",
	"Nizhny Novgorod":  "Нижній Новгород",
	"Ufa":              "Уфа",
	"Chelyabinsk":      "Челябінськ",
	"Samara":           "Самара",
	"Voronezh":         "Воронеж",
	"Volgograd":        "Волгоград",
	"Astana":           "Астана",
	"Almaty":           "Алмати",
	"Semey":            "Семей",
	"Pavlodar":         "Павлодар",
	"Shymkent":         "Шимкент",
	"Aktobe":           "Актобе",
	"Karaganda":        "Караганда",
	"Taraz":            "Тараз",
	"Ust-Kamenogorsk":  "Усть-Каменогорськ",
	"Atyrau":           "Атирау",
	"Minsk":            "Мінськ",
	"Gomel":            "Гомель",
	"Mogilev":          "Могильов",
	"Vitebsk":          "Вітебськ",
	"Grodno":           "Гродно",
	"Brest":            "Брест",
	"Bobruisk":         "Бобруйськ",
	"Baranovichi":      "Барановичі",
	"Borisov":          "Борисів",
	"Kyiv":            "Київ",
	"Kharkiv":         "Харків",
	"Odesa":           "Одеса",
	"Dnipro":          "Дніпро",
	"Donetsk":         "Донецьк",
	"Lviv":            "Львів",
	"Zaporizhzhia":    "Запоріжжя",
	"Kryvyi Rih":      "Кривий Ріг",
	"Mykolaiv":        "Миколаїв",
	"Luhansk":         "Луганськ",
	"Mariupol":        "Маріуполь",
	"Kherson":         "Херсон",
	"Vinnytsia":       "Вінниця",
	"Poltava":         "Полтава",
	"Chernihiv":       "Чернігів",
	"Cherkasy":        "Черкаси",
	"Zhytomyr":        "Житомир",
	"Sumy":            "Суми",
	"Khmelnytskyi":    "Хмельницький",
	"Rivne":           "Рівне",
	"Ternopil":        "Тернопіль",
	"Ivano-Frankivsk": "Івано-Франківськ",
	"Lutsk":           "Луцьк",
	"Chernivtsi":      "Чернівці",
}

func init() {
	messageCatalog[domain.LanguageUkrainian] = messageCatalogUkrainian
	buttonCatalog[domain.LanguageUkrainian] = buttonCatalogUkrainian
	labelCatalog[domain.LanguageUkrainian] = labelCatalogUkrainian
	cityLabels[domain.LanguageUkrainian] = cityLabelsUkrainian
	buttonEmojiOverrides[btnLanguageUkrainian] = ""
}
